discarding /home/gretatu/.conda/envs/bs/bin from PATH
prepending /home/gretatu/.conda/envs/brainmodeling/bin to PATH
/home/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainio_base/assemblies.py:213: FutureWarning: The inplace argument has been deprecated and will be removed in a future version of xarray.
  xr_data.set_index(append=True, inplace=True, **coords_d)
layers:   0%|          | 0/25 [00:00<?, ?it/s]layers:   0%|          | 0/25 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/home/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/transformers/configuration_utils.py", line 243, in get_config_dict
    raise EnvironmentError
OSError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gretatu/.conda/envs/brainmodeling/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/gretatu/.conda/envs/brainmodeling/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "neural_nlp/__main__.py", line 32, in <module>
    fire.Fire(command=FIRE_FLAGS)
  File "/home/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/home/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/fire/core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "neural_nlp/__main__.py", line 22, in run
    score = score_function(model=model, layers=layers, subsample=subsample, benchmark=benchmark)
  File "/home/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/result_caching/__init__.py", line 62, in wrapper
    result = function(*args, **kwargs)
  File "/om/user/gretatu/neural-nlp/neural_nlp/__init__.py", line 36, in score
    layer_score = benchmark_impl(candidate)
  File "/home/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/utils/__init__.py", line 80, in __call__
    return self.content(*args, **kwargs)
  File "/om/user/gretatu/neural-nlp/neural_nlp/benchmarks/neural.py", line 513, in __call__
    model_activations = listen_to(candidate, stimulus_set, reset_column='passage_id')
  File "/om/user/gretatu/neural-nlp/neural_nlp/benchmarks/neural.py", line 618, in listen_to
    story_activations = candidate(stimuli=story_stimuli, average_sentence=average_sentence)
  File "/om/user/gretatu/neural-nlp/neural_nlp/__init__.py", line 55, in __call__
    self._model(*args, **kwargs, layers=self._prerun)
  File "/home/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/utils/__init__.py", line 79, in __call__
    self._ensure_loaded()
  File "/home/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/utils/__init__.py", line 73, in _ensure_loaded
    self.content = self.load_fnc()
  File "/om/user/gretatu/neural-nlp/neural_nlp/models/implementations.py", line 1159, in model_instantiation
    config = config_ctr.from_pretrained(configuration['weight_identifier'])
  File "/home/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/transformers/configuration_utils.py", line 201, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/transformers/configuration_utils.py", line 252, in get_config_dict
    raise EnvironmentError(msg)
OSError: Can't load config for 'xlnet-large-cased'. Make sure that:

- 'xlnet-large-cased' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'xlnet-large-cased' is the correct path to a directory containing a config.json file


